Improve "How to test" sections of criteria
publiccodenet/standard pull request #672
Opened 2022-07-19 14:08 UTC by ericherman

fixes #314

2022-07-21 06:37 UTC, Ainali requested changes
Some tiny wordsmithing needed, but in general, this is great!

2022-07-21 06:37 UTC, Ainali commented on criteria/document-maturity.md
> +* Confirm that is clear where to get the newest version.
```suggestion
* Confirm that it is clear where to get the newest version.
```

2022-07-21 06:37 UTC, Ainali commented on criteria/make-contributing-easy.md
> +* Confirm the codebase contains links to the public issue tracker and submitted codebase changes.
```suggestion
* Confirm that the codebase contains links to the public issue tracker and submitted codebase changes.
```

2022-07-21 06:37 UTC, Ainali commented on criteria/make-contributing-easy.md
> +* Confirm that it is possible to participate in a discussion with other users about the software using channels described in the codebase.
```suggestion
* Confirm that it is possible to participate in a discussion with other users and developers about the software using channels described in the codebase.
```

2022-07-21 06:37 UTC, Ainali commented on criteria/open-standards.md
> +* Confirm that any non-open standards used are clearly documentation as such.
```suggestion
* Confirm that any non-open standards used are clearly documented as such.
```

2022-07-21 06:37 UTC, Ainali commented on criteria/open-to-contributions.md
> +* Check for list of involved organizations.
```suggestion
* Check for a list of involved organizations.
```

2022-07-21 06:37 UTC, Ainali commented on criteria/require-review.md
> +* Check with reviews if they run the code and tests during review.
```suggestion
* Check with reviewers if they run the code and tests during review.
```

2022-07-25 15:53 UTC, ElenaFdR commented on criteria/documenting.md
> +* Check that the documentation quality is part of integration testing, for instance documentation is generated from code and links and images are tested.
More colloquial; might be less familiar to a non-native English speaker.
```suggestion
* Check that the documentation quality is part of integration testing, for example documentation is generated from code and links and images are tested.
```

2022-07-25 15:56 UTC, ElenaFdR commented on criteria/open-licenses.md
> +* Confirm that contribution guidelines and repository configuration does not require transfer of copyright.
```suggestion
* Confirm that contribution guidelines and repository configuration do not require transfer of copyright.
```

2022-07-25 15:57 UTC, ElenaFdR commented on criteria/open-standards.md
> +* Confirm that data exchange follows an OSI approved open standard.
Add hyperlink to OSI-approved list.

2022-07-27 10:03 UTC, Ainali approved these changes

2022-07-27 10:04 UTC, merged