Label maturity as beta instead of draft
publiccodenet/standard pull request #706
Opened 2022-09-19 10:43 UTC by Ainali

Fixes #704

Added extra documentation so that it also shows on the web and in the repository.

2022-09-19 10:55 UTC, ericherman requested changes

2022-09-19 10:55 UTC, ericherman commented on print-cover.html
> +        <p><strong>Beta</strong><br/>Version {{ site.version }}</p>
In the context of a document, the word "Draft" is more meaningful than "Beta" for most readers.
As such, I'd suggest we continue to say "Draft" in bold and perhaps add "beta" after the version.

2022-09-19 14:27 UTC, Ainali commented
_This comment is partly a summary of a discussion @ericherman and I had this morning._
I should have noted that the footers pulls in "pre-release" from GitHub, which is another status we mention in the Standard. However, [GitHub documentation](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) states "To notify users that the release is not ready for production and may be unstable" which corresponds better to our definitions of prototype and alpha.

That poses the question if we should uncheck that box? And if we do, do we want to be more explicit on the [release page](https://github.com/publiccodenet/standard/releases) and how would we do that? 

A common way to do it with [Semantic versioning](https://semver.org/) is to append something to the end of the version number, for example **0.4.0-beta**.  If we used that, we wouldn't need to repeat it in text in other places.
After some thinking, I like this solution more and more.

2022-11-30 14:13 UTC, Ainali commented
Superseded by #729

2022-11-30 14:13 UTC, closed without merging