unlink glossary terms in review template
publiccodenet/standard pull request #880
Opened 2023-03-08 10:54 UTC by ericherman

Since b60c9c4 fewer of the criteria have glossary terms linked. The remaining ones now are out-of-place.
This unlinks those pages for now.
If we want links, we should ensure the first usage of each term is linked.

2023-03-08 11:54 UTC, Ainali requested changes
Still seem to generate some glossary links. For example in Code in the open I get 

```
Documenting which source code or policy underpins any specific interaction the [general public](../glossary.md#general-public) may have with an organization is OPTIONAL. |  |
```

2023-03-15 10:54 UTC, ericherman commented
> Still seem to generate some glossary links.

I'm not able to reproduce that error. I've updated the result as a separate commit.

2023-03-15 11:18 UTC, Ainali approved these changes
I can't reproduce it either anymore. I wonder if I briefly was in a weird state.

2023-03-15 11:48 UTC, ericherman commented
Okay, I'm glad that it's not just "it works on my box" ... I suggest we merge as-is.

2023-03-15 11:51 UTC, merged